#test
*analise*

In [4]:
from configs.funcoes import ler_csv
import pandas as pd
import plotly.express as px

df = ler_csv('Customer Loyalty History.csv')
display(df)

,Loyalty Number,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
0,480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,83236.0,Married,Star,3839.14,Standard,2016,2,NaN,NaN
1,549612,Canada,Alberta,Edmonton,T3G 6Y6,Male,College,NaN,Divorced,Star,3839.61,Standard,2016,3,NaN,NaN
2,429460,Canada,British Columbia,Vancouver,V6E 3D9,Male,College,NaN,Single,Star,3839.75,Standard,2014,7,2018.0,1.0
3,608370,Canada,Ontario,Toronto,P1W 1K4,Male,College,NaN,Single,Star,3839.75,Standard,2013,2,NaN,NaN
4,530508,Canada,Quebec,Hull,J8Y 3Z5,Male,Bachelor,103495.0,Married,Star,3842.79,Standard,2014,10,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16732,823768,Canada,British Columbia,Vancouver,V6E 3Z3,Female,College,NaN,Married,Star,61850.19,Standard,2012,12,NaN,NaN
16733,680886,Canada,Saskatchewan,Regina,S1J 3C5,Female,Bachelor,89210.0,Married,Star,67907.27,Standard,2014,9,NaN,NaN
16734,776187,Canada,British Columbia,Vancouver,V5R 1W3,Male,College,NaN,Single,Star,74228.52,Standard,2014,3,NaN,NaN
16735,906428,Canada,Yukon,Whitehorse,Y2K 6R0,Male,Bachelor,-57297.0,Married,Star,10018.66,2018 Promotion,2018,4,NaN,NaN
16736,652627,Canada,Manitoba,Winnipeg,R2C 0M5,Female,Bachelor,75049.0,Married,Star,83325.38,Standard,2015,12,2016.0,8.0

In [5]:
df = df.drop(columns='Loyalty Number')
df = df.dropna()
display(df)
display(df.info())

,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
31,Canada,Ontario,Ottawa,K1F 2R2,Female,Bachelor,51375.0,Married,Star,3893.31,Standard,2015,4,2015.0,12.0
39,Canada,British Columbia,Vancouver,V5R 1W3,Female,Bachelor,54460.0,Married,Star,3911.12,Standard,2017,3,2017.0,4.0
45,Canada,Ontario,Thunder Bay,K8T 5M5,Female,Bachelor,80697.0,Married,Star,3919.37,Standard,2016,6,2017.0,2.0
51,Canada,Ontario,Sudbury,M5V 1G5,Female,Bachelor,73236.0,Single,Star,3924.42,Standard,2016,11,2017.0,7.0
65,Canada,Alberta,Edmonton,T9G 1W3,Female,Bachelor,30486.0,Divorced,Aurora,5391.97,2018 Promotion,2018,3,2018.0,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16676,Canada,Yukon,Whitehorse,Y2K 6R0,Female,Bachelor,74049.0,Divorced,Nova,13009.24,2018 Promotion,2018,3,2018.0,11.0
16678,Canada,Manitoba,Winnipeg,R6Y 4T5,Female,Bachelor,46607.0,Married,Star,34611.38,Standard,2016,6,2017.0,2.0
16713,Canada,British Columbia,West Vancouver,V6V 8Z3,Male,Bachelor,88356.0,Married,Star,40235.97,Standard,2016,5,2017.0,1.0
16730,Canada,Ontario,Toronto,M1R 4K3,Female,Bachelor,76778.0,Single,Star,58166.55,Standard,2015,1,2015.0,9.0
16736,Canada,Manitoba,Winnipeg,R2C 0M5,Female,Bachelor,75049.0,Married,Star,83325.38,Standard,2015,12,2016.0,8.0

<class 'pandas.DataFrame'>
Index: 1540 entries, 31 to 16736
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Country             1540 non-null   str
 1   Province            1540 non-null   str
 2   City                1540 non-null   str
 3   Postal Code         1540 non-null   str
 4   Gender              1540 non-null   str
 5   Education           1540 non-null   str
 6   Salary              1540 non-null   float64
 7   Marital Status      1540 non-null   str
 8   Loyalty Card        1540 non-null   str
 9   CLV                 1540 non-null   float64
 10  Enrollment Type     1540 non-null   str
 11  Enrollment Year     1540 non-null   int64
 12  Enrollment Month    1540 non-null   int64
 13  Cancellation Year   1540 non-null   float64
 14  Cancellation Month  1540 non-null   float64
dtypes: float64(4), int64(2), str(9)
memory usage: 192.5 KB

None

In [6]:

for coluna in df.columns:
    grafico = px.histogram(df, x=coluna, y='Salary', color='Gender')
    grafico.show()